# Generated by Django 6.0 on 2025-12-15 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '文件审批',
                'verbose_name_plural': '文件审批',
                'db_table': 'document_approval',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '文件标签',
                'verbose_name_plural': '文件标签',
                'db_table': 'document_tag',
            },
        ),
        migrations.CreateModel(
            name='DocumentTagRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件标签关联',
                'verbose_name_plural': '文件标签关联',
                'db_table': 'document_tag_relation',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('original_name', models.CharField(max_length=200, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('zip', '压缩包')], max_length=20, verbose_name='文件类型')),
                ('category', models.CharField(choices=[('bidding', '招投标'), ('contract', '合同'), ('achievement', '成果资料'), ('process', '过程资料'), ('original', '原始资料'), ('handover', '资料交接清单')], max_length=50, verbose_name='文件分类')),
                ('minio_path', models.CharField(max_length=500, verbose_name='MinIO存储路径')),
                ('minio_bucket', models.CharField(max_length=100, verbose_name='MinIO存储桶')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('tags', models.JSONField(blank=True, default=list, help_text='文件标签数组', verbose_name='标签')),
                ('related_files', models.JSONField(blank=True, default=list, help_text='关联文件ID数组', verbose_name='关联文件')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='documentManager.document', verbose_name='父版本')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'document',
            },
        ),
    ]
