# Generated by Django 6.0 on 2025-12-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentManager', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='documentManager.document', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='documenttagrelation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='documentManager.document', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='documenttagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_relations', to='documentManager.documenttag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'category'], name='document_project_0ebd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploader'], name='document_uploade_7049ff_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['approval_status'], name='document_approva_fa6884_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['document'], name='document_ap_documen_37755d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['approver', 'approval_status'], name='document_ap_approve_2cd7b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttagrelation',
            unique_together={('document', 'tag')},
        ),
    ]
