# Generated by Django 6.0 on 2025-12-15 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManager', '0002_initial'),
        ('project', '0002_alter_projectmemberpermission_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='document_project_0ebd4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='document_approva_fa6884_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(help_text='第二层分类：根据 file_type 选择对应的分类选项', max_length=50, verbose_name='文件分类'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('file', '文件'), ('zip', '压缩包')], help_text='第一层分类：file 或 zip', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'file_type', 'category'], name='document_project_3228f1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='document_created_71db36_idx'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='approval_time',
        ),
        migrations.RemoveField(
            model_name='document',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
    ]
