# Generated by Django 6.0 on 2025-12-15 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('approval', '立项'), ('bidding', '招投标'), ('implementation', '实施'), ('delivery', '交付'), ('completion', '结项'), ('archived', '归档')], default='approval', max_length=20, verbose_name='项目状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='项目开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='项目结束时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='userManager.department', verbose_name='所属部门')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='MemberJoinApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('join_type', models.CharField(choices=[('user_apply', '用户申请'), ('admin_invite', '管理员邀请')], max_length=20, verbose_name='加入类型')),
                ('admin_approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='管理员审批状态')),
                ('user_approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='用户确认状态')),
                ('admin_approval_time', models.DateTimeField(blank=True, null=True, verbose_name='管理员审批时间')),
                ('user_approval_time', models.DateTimeField(blank=True, null=True, verbose_name='用户确认时间')),
                ('admin_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approvals', to=settings.AUTH_USER_MODEL, verbose_name='管理员审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请/被邀请用户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_approvals', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '成员加入审批',
                'verbose_name_plural': '成员加入审批',
                'db_table': 'member_join_approval',
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permission_status', models.CharField(choices=[('active', '有效'), ('disabled', '已禁用'), ('pending', '待审批')], default='active', max_length=20, verbose_name='权限状态')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='项目内职位')),
                ('permissions', models.JSONField(default=list, help_text='权限操作类型：["view", "download", "upload", "modify", "delete"]', verbose_name='权限')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='有效期开始时间')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='有效期结束时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='project.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员权限',
                'verbose_name_plural': '项目成员权限',
                'db_table': 'project_member_permission',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_37437c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='project_code_e1dc96_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='project_manager_2eed63_idx'),
        ),
        migrations.AddIndex(
            model_name='memberjoinapproval',
            index=models.Index(fields=['user', 'project'], name='member_join_user_id_6a9857_idx'),
        ),
        migrations.AddIndex(
            model_name='memberjoinapproval',
            index=models.Index(fields=['admin_approval_status', 'user_approval_status'], name='member_join_admin_a_38f781_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemberpermission',
            index=models.Index(fields=['user'], name='project_mem_user_id_2027d4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemberpermission',
            index=models.Index(fields=['project'], name='project_mem_project_8e1c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemberpermission',
            index=models.Index(fields=['user', 'project', 'permission_status'], name='project_mem_user_id_b9c63b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmemberpermission',
            unique_together={('user', 'project')},
        ),
    ]
