# Generated by Django 6.0 on 2025-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberpermission',
            name='position',
            field=models.CharField(default='项目成员', max_length=50, verbose_name='项目内职位'),
        ),
    ]
